name: Deploy Flutter Web

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Clean old build
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Deploy
        run: |
          cd build/web
          git init
          git config --global user.email ariel.betti@gmail.com
          git config --global user.name arielbetti
          git status
          git remote add origin https://${{secrets.TOKEN}}@github.com/ArielBetti/rick_and_morty_flutter
          git checkout -b gh-pages-web
          git add .
          git commit -m "update"
          git push origin gh-pages-web -f
